name: attendbot
description: Automatic Attendance Bot - Android & iOS
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0
  webview_flutter_android: ^4.0.0
  webview_flutter_wkwebview: ^3.14.0
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^16.3.3
  permission_handler: ^11.3.1
  connectivity_plus: ^6.1.5
  workmanager: ^0.5.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
